In [1]:
import pandas as pd

df = pd.read_csv('e_commerce_store.csv')

In [2]:
df.head()

,Date,Region,Brand,Product,Product Type,Sales,Profit,Units Sold,Discount (%),Customer Rating
0,4/11/2023,South,Brand C,Product 2,Home Appliances,4574.16,1642.07,152,19.76,3.40
1,4/27/2023,West,Brand A,Product 3,Consumer Goods,12631.78,4172.09,398,17.93,4.48
2,4/8/2023,East,Brand A,Product 5,Electronics,9884.40,3448.69,320,11.71,4.65
3,2/5/2023,West,Brand B,Product 1,Electronics,5344.99,1926.96,156,21.74,3.01
4,8/9/2023,West,Brand A,Product 2,Electronics,4890.45,1682.51,121,14.40,3.57

In [3]:
df.describe()

              Sales       Profit  Units Sold  Discount (%)  Customer Rating
count    698.000000   698.000000  698.000000    698.000000       698.000000
mean    7358.320559  2488.094527  226.717765     12.757794         3.663438
std     3094.972508  1004.723565   98.300869      6.818527         0.651065
min     1254.220000   401.080000   50.000000      1.010000         1.860000
25%     4966.182500  1717.845000  148.000000      6.580000         3.212500
50%     7355.240000  2458.860000  225.000000     12.910000         3.650000
75%     9862.620000  3289.300000  307.000000     18.790000         4.150000
max    13641.030000  4455.560000  399.000000     24.890000         5.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             698 non-null    object
 1   Region           698 non-null    object
 2   Brand            698 non-null    object
 3   Product          698 non-null    object
 4   Product Type     698 non-null    object
 5   Sales            698 non-null    float64
 6   Profit           698 non-null    float64
 7   Units Sold       698 non-null    int64
 8   Discount (%)     698 non-null    float64
 9   Customer Rating  698 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 54.7+ KB

In [5]:
df.shape

(698, 10)

In [6]:
!pip install plotly

Requirement already satisfied: plotly in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (7.1.0)
Requirement already satisfied: narwhals>=1.15.1 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from plotly) (25.0)

In [8]:
!pip install nbformat

Requirement already satisfied: nbformat in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (5.11.1)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from nbformat) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /opt/anaconda3/envs/networks/lib/python3.11/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.16.0)

In [9]:
import plotly.express as px


brand_counts = df['Brand'].value_counts().reset_index()
brand_counts.columns = ['Brand', 'Count']  # Rename columns for clarity

# Create a bar chart
fig_brand_counts = px.bar(brand_counts,
                      	x='Brand', y='Count',
                      	labels={'Brand': 'Brand', 'Count': 'Frequency'},
                      	title='Frequency of Each Brand',
                      	color='Brand',
                      	text='Count',  # Add labels above the bars
                      	height=600,  # Resize height
                      	width=1000)  # Resize width
fig_brand_counts.update_traces(textposition='outside')  # Position the labels outside the bars
fig_brand_counts.show()

In [11]:
import plotly.express as px

region_sales = df.groupby('Region')['Sales'].sum().reset_index()

# Create a bar chart for sales by region
fig_region = px.bar(region_sales,
                	x='Region', y='Sales',
                	labels={'Region': 'Region', 'Sales': 'Total Sales'},
                	title='Total Sales by Region',
                	color='Region',
                	text='Sales',  # Add labels above the bars
                	height=600,  # Resize height
                	width=700)  # Resize width
fig_region.update_traces(texttemplate='%{text:.2s}', textposition='outside')  # Shortened text format
fig_region.show()